title: Thesis & Research Supervision
description: "Resources and guidance for thesis and research supervision under Dr. Steven Denney"
theme: jekyll-theme-cayman
baseurl: /thesis-supervision
show_downloads: false

kramdown:
  parse_block_html: true
